#database configuration
spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/employee}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
