#database configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/employee_challenge
    username: root
    password: BHU*nji9
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
